version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vigil-hashi-vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl
      - ./data:/vault/file
    command: vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
